### PR TITLE
Add check for required arguments for Sequence construction

### PR DESCRIPTION
**Pull request by akalsi87**

### CODE REVIEW

**Comment by dgoffredo** [comment]
Thanks for contributing.

Requiring non-optional and list-valued attributes to be specified during initialization makes strong assumptions about the codecs that will be used with `Sequence`, and even which conventions are used within a codec (such as whether, in JSON, to encode empty arrays or to encode `None` as `null`).

The issue, I think, lies in that `from_jsonable` utilizes the target type's `__init__`. Maybe what you're going for is the idea that `__init__` is for humans, and so should require a value for every attribute, while codecs are given more leniency and so use a different constructor.

But then we have two constructors instead of one. :(

Another thing that might be worth trying is this: require all attributes to be present when initializing a `Sequence` (though I would enforce this in `Sequence.__init__`, not in `__init_subclass__`), but then split the "`Sequence` or `Choice`" clause of `from_jsonable` in two. Treat `Sequences` in a special way, where we add the logic "look to see whether there are any nullable or list-valued attributes that are missing from the input, and if so inject default (`None` or `[]`) values." This way, when a human uses `__init__`, he has to specify everything, whereas in `from_jsonable`, less strict encoding conventions are tolerated.

On an unrelated note,  your code's requirement that class annotation values not be strings I think is too strong, since strings are used for user-defined types to avoid issues caused by cyclic type dependencies.

Tonight or tomorrow, I'll submit my own pull request demonstrating the ideas I mentioned above.

**Comment by dgoffredo** [comment]
Also, `Sequence` and `Choice` need `__repr__` methods; using them in the python repl is a pain.

**Comment by akalsi87** [comment]
I think non-optional values should be specified. I do make assumptions about attributes that are list have a default empty list value. I do not rely on this in the code [however](https://github.com/dgoffredo/stag/pull/5/files#diff-d43ea65474d2b3b4c91db09684ac4861R33).

The default list and none values should be inherited by every object through the class definition and inheriting the class attributes. So the truly required arguments are being checked for, whether from the codec, or from a user, although I concede that this bothered me at the REPL. Am I missing something here?

I understand that the annotations being strings is an issue. I hope Python 3.7 solves that one.

**Comment by akalsi87** [comment]
The reliance on the attribute annotation being a type can be removed [here](https://github.com/dgoffredo/stag/pull/5/files#diff-d43ea65474d2b3b4c91db09684ac4861R28) as, in the very next line, I do convert to a string. 😄

**Comment by dgoffredo** [comment]
If messages (responses) are coming from the C++ zone, then empty arrays and nulls might be missing. It's the default. See the table in https://bloomberg.github.io/bde/group__baljsn__encoderoptions.html

Yeah I think I'm not seeing what you're seeing. Let's talk about it in person next week.

**Comment by dgoffredo** [comment]
Thanks for playing

**Pull request merged**
